.TH "Job" 3 "Terça, 29 de Março de 2022" "Version v1.2" "Flexible Job Shop Problem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Job \- Estrutura de dados para a lista de trabalhos\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "struct \fBJob\fP * \fBnext\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Estrutura de dados para a lista de trabalhos\&. 
.SH "Documentação dos campos e atributos"
.PP 
.SS "int id"

.SS "struct \fBJob\fP* next"


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Flexible Job Shop Problem a partir do código fonte\&.
